name: Multi-OS Python Tests
on:
  push:
    branches: [main_dashboard_cm]
  pull_request:
    branches: [main_dashboard_cm]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.6"]
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      # - name: Validate package
      #   run: show_dashboard
